---
apiVersion: "v1"
kind: "Event"
metadata:
  labels:
    entando.org/entando-resource-namespace: "my-namespace"
    entando.org/entando-resource-kind: "EntandoApp"
    EntandoApp: "my-app"
  name: "my-app-29189290"
  namespace: "my-namespace"
  ownerReferences:
  - apiVersion: "entando.org/v1"
    kind: "EntandoApp"
    blockOwnerDeletion: true
    controller: true
    name: "my-app"
    uid: "493cfb25-1d8d-4177-86fd-5fc9c7f823a7"
action: "FAILED"
count: 1
firstTimestamp: "2021-08-06T15:03:50Z"
involvedObject:
  apiVersion: "entando.org/v1"
  kind: "EntandoApp"
  fieldPath: "status"
  name: "my-app"
  namespace: "my-namespace"
  resourceVersion: "8297716"
  uid: "493cfb25-1d8d-4177-86fd-5fc9c7f823a7"
lastTimestamp: "2021-08-06T15:03:50Z"
message: "The deployment of EntandoApp my-namespace/my-app failed due to Fake Controller\
  \ Exception. Fix the root cause and then trigger a redeployment by adding the annotation\
  \ 'entando.org/processing-instruction: force'"
reason: "Failed"
related:
  apiVersion: "v1"
  kind: "Pod"
  name: "entando-k8s-entando-k8s-app-con-hhrv4-55-from-build-pack--9w6sc"
  namespace: "controller-namespace"
source:
  component: "entando-k8s-app-controller"
type: "Error"
